feat: add dockerfile and nginx config
gravity-ui/page-constructor-website-template pull request #1
Opened 2023-04-12 11:22 UTC by gorgeousvlad

2023-04-17 09:28 UTC, ismd requested changes

2023-04-17 09:28 UTC, ismd commented on deploy/nginx/sites-enabled/main.conf
> +server {
Сервисо-специфичный конфиг это по идее. У нас по-другому совсем выглядит конфиг nginx. Думаю это не надо в общий образ зашивать.

2023-04-17 09:28 UTC, ismd commented on deploy/supervisor/supervisor.conf
> +[supervisord]
Думаю, что этот файл тоже не общий в сервисах. Нода по-разному запускается. У нас нету next совсем например. Мне кажется, что этот конфиг лишний в общем образе.

2023-04-17 09:28 UTC, ismd commented on dev/nginx.template.conf
> +    location /_next/static/ {
Это, конечно, шаблон. Но я тоже думаю, что это лишнее в общем образе. Здесь явно завязка на next, который есть не у всех. Думаю такой шаблон не нужен на общем для всех уровне.

2023-04-17 09:28 UTC, ismd commented on Dockerfile
> +FROM node:18
Имхо не оч круто если мы наследуемся в базовом образе от образа, который сам не является базовым. Мы здесь завязываемся на ноду, но скорее необходимо завязываться на ОС. Вдруг так случится и node:20 в будущем будет с новой ОС под капотом, нам это будет очень больно.

2023-06-27 12:45 UTC, gorgeousvlad commented on deploy/nginx/sites-enabled/main.conf
> +server {
there was a test pr, now base docker image Dockerfile lives here
https://github.com/gravity-ui/docker-nodejs

in this project I left only code for website template

2023-06-29 19:23 UTC, NikitaCG requested changes

2023-06-29 19:23 UTC, NikitaCG commented on dev/nginx.template.conf
> +    location /_next/static/ {
we can add parts about next to separate configs and leave a comment that they can be inserted here if necessary and write about it in the README

2023-06-30 08:34 UTC, gorgeousvlad commented on dev/nginx.template.conf
> +    location /_next/static/ {
but it i always necessary till it's nextjs based teplate

2023-06-30 08:42 UTC, NikitaCG approved these changes

2023-06-30 08:43 UTC, merged